# Generated by Django 4.1.7 on 2024-08-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityinfos',
            old_name='sezes',
            new_name='sizes',
        ),
    ]
