# Generated by Django 4.1.7 on 2024-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfos',
            name='commodity_infos_id',
            field=models.IntegerField(verbose_name='商品信息表的主键 id'),
        ),
        migrations.AlterField(
            model_name='cartinfos',
            name='user_id',
            field=models.IntegerField(verbose_name='Django 内置用户表的主键 id'),
        ),
    ]
